# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464e45be0dc121e15fe1231c4cc34f5630a077ccbfa13123315ce963ec69cbeac0af5e579e61df6d7b1aabce7a643830e30ed9b04613f17c8ddb37d7ffc99133

test:
  secret_key_base: edd9a81dcc6dd5d61b050c39374173f3a6bfdca1f3422267c409a3764a2641e783d569bf53e38237121a99263f3d7db77c2de53558d566e33f397dda24dc10b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
